export default [{
    url: '/tools/json',
    name: 'JSON格式化',
    icon: '/static/images/tools/json.png',
    stars: 5
}, {
    url: '/tools/sql',
    name: 'SQL格式化',
    icon: '/static/images/tools/sql.png',
    stars: 4
}, {
    url: '/tools/xml',
    name: 'XML格式化',
    icon: '/static/images/tools/xml.png',
    stars: 4
}, {
    url: '/tools/thumb',
    name: '生成缩略图',
    icon: '/static/images/tools/thumb.png',
    stars: 5
}, {
    url: '/tools/idNoQry',
    name: '身份证查询',
    icon: '/static/images/tools/idNoQry.png',
    stars: 5
}, {
    url: '/tools/seal',
    name: '电子印章',
    icon: '/static/images/tools/seal.png',
    stars: 5
}, {
    url: '/tools/idNoGen',
    name: '生成身份证',
    icon: '/static/images/tools/idNoGen.png',
    stars: 5
}, {
    url: '/tools/gif',
    name: '制作Gif',
    icon: '/static/images/tools/gif.png',
    stars: 5
}, {
    url: '/tools/img',
    name: '图片解析',
    icon: '/static/images/tools/img.png',
    stars: 5
}, {
    url: '/tools/bazi',
    name: '五行、八字',
    icon: '/static/images/tools/bazi.png',
    stars: 5
}];
